### PR TITLE
V0.1/41 if syntax

### PR DESCRIPTION
**Pull request by sfkleach**
This pull request adds the if-syntax to Nutmeg. It is also the basis of [the detailed walkthrough](/Spicery/Nutmeg/wiki/HOW-TO-Add-a-New-Language-Feature) on how to add features to Nutmeg.

### CODE REVIEW

**Comment by philallen117** [comment]
I have not figured how the flexible syntax (`then:`, `then`, `:`) works, yet. I will have to go back to it.

I need to understand parser better before I can mess with it. (I used parser generators before. I read up on parser combinator libraries in Haskell, but reading was all it was.) I think it is sort of look ahead 1 and the 'must' is the way to force a backtrack. Is that right?

And I have not used the features of regexp that tokenizer uses, so I will need to look them up, too.

The visitor pattern stuff in codetree - as a matter of style, are you sticking to creating new values, or also doing some 'modify in place' for stages that purely enrich their input but do not delete or restructure nodes?

Looking at the Java-level verbosity of what are mostly data classes, is namedtuple any use? It generates a class that is basically no different from the code you would write by hand. Only thing is that to add additional methods, you have to subclass it one more time. I don't know enough about Python to know whether that means dispatch then takes longer for the generated CRUD methods. I could time some stuff if you are interested.

Is there work waiting on the resolver? The test resolver has what looks like a remaining ignore.

**Comment by sfkleach** [comment]
> I have not figured how the flexible syntax (`then:`, `then`, `:`) works, yet. I will have to go back to it.

The intention is that the base syntax is `if E then S (elseif E then S)* (else S)? endif`, which we could call the "base form" to give it a name. Then, following Python to reduce verbosity, we allow `:` to substitute for the `then` and simply for consistency with Python we allow `:` to follow `else`. 

The guiding rule is that "punctuation" keywords, like `then`, may be abbreviated to a `:` when they follow an expression but not when they follow a statement. This not only corresponds to the Python rule but is kind to human readers.

At the moment I am also allowing `:` to follow all punctuation-keywords. That's why `then:` and `else:` are allowed.

> I need to understand parser better before I can mess with it. (I used parser generators before. I read up on parser combinator libraries in Haskell, but reading was all it was.) I think it is sort of look ahead 1 and the 'must' is the way to force a backtrack. Is that right?

I don't use a parser generator but a recursive descent parser with precedence. It's simple, fast, efficient and most importantly can be tweaked to give decent error messages. If you take a look at https://github.com/Spicery/Nutmeg/wiki/HOW-TO-Add-a-New-Language-Feature I do give some explanation there. But the core algorithm is explained here https://github.com/Spicery/Nutmeg/wiki/Recursive-Descent-Parser. 

> And I have not used the features of regexp that tokenizer uses, so I will need to look them up, too.

No they were new to me too. That was an interesting direction Zack took. I usually hand-code a FSA, which has the massive advantage of constructing the token as it goes and generating excellent error messages. But this was interesting - but deeply flawed by the limitations of Python's regex engine. In fact it's so badly flawed that it's borderline unworkable & maybe we'll need to rethink down the line. But it's working fine for now.

> 
> The visitor pattern stuff in codetree - as a matter of style, are you sticking to creating new values, or also doing some 'modify in place' for stages that purely enrich their input but do not delete or restructure nodes?
> 
> Looking at the Java-level verbosity of what are mostly data classes, is namedtuple any use? It generates a class that is basically no different from the code you would write by hand. Only thing is that to add additional methods, you have to subclass it one more time. I don't know enough about Python to know whether that means dispatch then takes longer for the generated CRUD methods. I could time some stuff if you are interested.

> Is there work waiting on the resolver? The test resolver has what looks like a remaining ignore.

Whoops! That is explained in the walkthrough but it should have had a comment in the code. I will fix that!

**Comment by sfkleach** [comment]
> I meant I have not understood the _code_ yet. Your syntax design makes a lot of sense. Sorry.

Oh I see - pardon me!

> Yes, this is my first recursive descent parser. (I came across Parsec etc., but that was only in the context of "monads - why bother?") Hoping it will be possible to give better error messages this way :-) I will look for some more general articles about them.

They were a popular way of writing parsers until the table-driven LALR parsers turned up. Both have their advantages - the table driven parsers are very powerful when you're doing ad hoc grammars (although I tend to use a variant of Earley's algorithm if I need a full CFG parser). I tend to stick with recursive descent because they give me nice control over the interaction between the parsing and code-tree construction. You tend to have better contextual information too, so error messages can be made quite good - although our parser is _definitely_ not an example of good error reporting yet!

 
> (My question about lookahead was how far the parser might have to backtrack, and whether it has to be careful to hold on to error messages until it knows that no production fits and it has picked the production(s) to report errors against.)

There's no backtracking at all in this parser style, although it is simple to add if you need it. If the parser needs to peek ahead a bit to make a choice, it can just peek at the token stream. You'll find a procedure called tryRead, which attempts to consume a token (of a given category) and returns `true` if it is successful. That's basically the only lookahead that's needed.

In the case of the `if` expression the grammar rule gets written like this - and I have added comments to show progress/
```python
def ifPrefixMiniParser( parser, token, source ):
    # if ^ EXPR then STMNTS ... endif
    testPart = parser.readExpr( math.inf, source )
    # if EXPR ^ then STMNTS ... endif
    mustRead( source, "THEN" )
    # if EXPR then ^ STMNTS ... endif
    thenPart = parser.readStatements( source )
    # if EXPR then STMNTS ^ (elseif EXPR then STATEMENTS ... | else STMNTS | )  endif
    if tryRead( source, "ELSE_IF" ):
        # if EXPR then STMNTS elseif ^ EXPR then STATEMENTS ... endif
        elsePart = ifPrefixMiniParser( parser, None, source )
        # if EXPR then STMNTS elseif EXPR then STATEMENTS .... endif ^
        return codetree.IfCodelet( testPart=testPart, thenPart=thenPart, elsePart=elsePart )
    elif tryRead( source, "ELSE" ):
        # if EXPR then STMNTS else ^ STMNTS endif
        elsePart = parser.readStatements( source )
        # if EXPR then STMNTS else STMNTS ^ endif
        mustRead( source, "END_IF" )
        # if EXPR then STMNTS else STMNTS endif ^
        return codetree.IfCodelet( testPart=testPart, thenPart=thenPart, elsePart=elsePart )
    else:
        # if EXPR then STMNTS ^ endif 
        mustRead( source, "END_IF" )
        # if EXPR then STMNTS endif ^
        return codetree.IfCodelet( testPart=testPart, thenPart=thenPart, elsePart=codetree.SeqCodelet() )
```

**Comment by sfkleach** [comment]
> The visitor pattern stuff in codetree - as a matter of style, are you sticking to creating new values, or also doing some 'modify in place' for stages that purely enrich their input but do not delete or restructure nodes?

Alas, I am using both. 

> Looking at the Java-level verbosity of what are mostly data classes, is namedtuple any use? It generates a class that is basically no different from the code you would write by hand. Only thing is that to add additional methods, you have to subclass it one more time. I don't know enough about Python to know whether that means dispatch then takes longer for the generated CRUD methods. I could time some stuff if you are interested.

The codetree is the complicated one and I don't think that namedtuples work for that (too much inheritance & too much JSON encode/decoding). So I would say skip that. But a lot of others might simplify nicely. By and large I am not worried about performance yet as we need to build something worth keeping first. Should we get some uptake or a sense that we would get uptake if performance wasn't rubbish then I would be inclined to rewrite in Go, Java or C# anyway. (I have done the full C++ runtime engine with Ginger and I wouldn't do the same again without commercial interest as it's a full-time activity.)

**Comment by sfkleach** [comment]
Comments added & pushed.

**Pull request merged**
